### PR TITLE
Merge, update from OpenBSD

### PR DESCRIPTION
**Pull request by katakk**

### CODE REVIEW

**Comment by slicer69** [comment]
I tried the merged code and it works (after I added stdlib.h to the parse.y file). But the persist keyword does not work on either my FreeBSD or Linux test system. Does it work for you? I'm thinking if not then we should remove references to the persist keyword from the documentation.

**Comment by abishai** [comment]
In FreeBSD we don't have TIOCCHKVERAUTH ioctl request in kernel.

**Comment by slicer69** [comment]
I guess that raises the question as to whether we can either get the request into the FreeBSD kernel or if there is a suitable workaround?

**Comment by slicer69** [comment]
I have merged these changes in, with minor updates to the documentation to make it clear the persist keyword will not work on FreeBSD or Linux at this time.

**Pull request closed without merging**
