### PR TITLE
Handle multiple users with same UID correctly

### PR DESCRIPTION
**Pull request by helmat**
There is a small issue with multiple user names having the same UID. For example, that is the case for FreeBSD: root and toor being UID 0 (toor has `/bin/sh` instead of `/bin/csh`). When looking up the pw entry, we should look on the specified user name (`-u` option) instead of the related UID which will usually match with the first pw entry already. For FreeBSD's root/toor case that would ensure that `doas -u toor` will set `SHELL` correctly to `/bin/sh`. Also we need to handle the case where pw_shell is empty (default shell = `/bin/sh`).

### CODE REVIEW

**Comment by slicer69** [comment]
This looks good. I'll give this patch a test run on my systems and, assuming everything goes well, merge this for the next release.

**Comment by slicer69** [comment]
Thanks for the patch, I've tested it on FreeBSD and Linux and both seem to be working as expected.

This patch raises an interesting question in my mind. Since both root and toor have the same UID it means someone with permission to act as root can also act as toor. Which I think makes sense. In other words if doas.conf has this line:

      permit slicer as root

Then slicer can use wither "doas -u root" or "doas -u toor" to perform a task.

Since they have the same UID, to me this makes sense. But I'm wondering: are there any situations in which someone should have access to toor, but not root? It seems not, but I'm wondering if this is a case we should watch for?

**Comment by helmat** [comment]
Indeed. The root/toor case in FreeBSD is a trivial one - just about a different shell. However, every passwd entry can carry a different class and that can influence a lot of things, locale or resource limits for example. In case login names are different but the UID is the same it's indeed an interesting question whether the "as" clause in doas.conf should refer to the UID (as it does currently, which implies that the login class of the first found UID will be used) or to the login name (which would inherit the login class associated with this login name). Maybe a clarification that the "as" clause refers to the UID behind the name is sensible?

**Comment by slicer69** [comment]
I think this makes sense. I'll update the doas.conf manual page (and maybe the doas page as well) to indicate "permit user as" picks the first user in case of matching UIDs.

**Pull request merged**
