### PR TITLE
fix the setusercontext(3) workaround

### PR DESCRIPTION
**Pull request by Duncaen**
Seeing this being used on even more system like Illumos with this ugly
and security critical bug open makes me cringe every time I check if it
was finally fixed.

I reported it directly to the maintainer in 2017. I reported it to
pkgsrc-security@netbsd.org without a response.

### CODE REVIEW

**Comment by slicer69** [comment]
Thanks for submitting the patch. Would you care to explain what it is you are trying to fix and why you feel it is a security issue? How is this an improvement over existing behaviour?

**Comment by Duncaen** [comment]
doas uses [setusercontext(3)](http://man.openbsd.org/setusercontext.3) with the `LOGIN_SETUSER` flag which does `setresuid(3)` and the `LOGIN_SETGROUP` flag which does `initgroups(3)` and `setresgid(2)`.
The codepath that is used when `HAVE_LOGIN_CAP_H` is not set, only does `setuid(2)` which only sets the uid, the `LOGIN_SETGROUP` path is completely left out.

This means your doas port does not drop the groups of the executing user.

1 .This is a big problem if you use doas to run a command with less privileges, which is very security critical, this is not the intended behavior as it is on openbsd, this drastically changes what doas actually does in those cases. (Last time I used a crontab entry to switch from root to a different user as example for such a use case.)
1. If you run a script or program which creates files or directory user and group editable, it will use the executing users group id, which could lead to unintended user writable files. 
1. When you have a umask set that would make it group readable, its not as expected root:root, its root:user.

The whole point I make is that this is wrong and doas and sudo change the group ids and making this port differ from this behavior without documenting and warning users is very very bad.

**Comment by slicer69** [comment]
I have a point of contention with the overall view. One being that I'm not sure this qualifies as a security concern. Having the group of the calling user is arguably expected, or at least certainly useful. However, I can see why, in some cases it would also be dangerous. I'm going to commit this patch and test it. Thank you for putting it together.

On a side note, I'd like to point out that my testing shows this issue, keeping the group of the original user, appears to only affect Linux. On FreeBSD group permissions were already dropped, as they were on OpenBSD, and (I think) NetBSD. Linux was the odd one out for keeping the calling user's groups. And I think this patch is worthwhile to bring Linux into the fold so it is no longer an exception.

**Comment by Duncaen** [comment]
> . On FreeBSD group permissions were already dropped, as they were on OpenBSD, and (I think) NetBSD. Linux was the odd one out for keeping the calling user's groups. And I think this patch is worthwhile to bring Linux into the fold so it is no longer an exception.

I'm not sure about NetBSD, I don't see where `HAVE_LOGIN_CAP_H` is defined (maybe its some magic variable that comes out of the pkgsrc build environment, but kind of doubt that).

There are several porting issues like that you replaced `strtonum` with `sscanf` and introduce undefined behaviour because `errstr` is uninitialized so that depending on compiler and how the stars align, parseuid and parsegid could return success or failure.
If its successful then instead of warning that the supplied uid in invalid it will fallback to root.
Bugs like this that are relatively easy to spot, even by compilers and static checks shouldn't happen in released versions of security critical software.

**Comment by Duncaen** [comment]
> Having the group of the calling user is arguably expected, or at least certainly useful.

It is definitively not, I don't see how you can make such a claim, this is just ridiculous. I don't see how you can simply ignore that the original doas and sudo would never do something like this and claim this is not security critical and in some way expected.
We define users to be part of certain groups using `/etc/groups` and just because its possible to ignore this when you are root doesn't mean it should be used, is intended or in any way useful.
If you want a user to be part of a group, you add that user to the group instead of having a tool that tricks its way around defined groups by abusing root capabilities.

I'll bet with you that anyone who is concerned about security would 100% agree with me that this is a security issue. Doesn't matter if its a OpenBSD developer, a system administrator who knows about how groups and users are supposed to work or someone InfoSec related.

**Pull request merged**
