### PR TITLE
Some linux fixes

### PR DESCRIPTION
**Pull request by amalleo25**
Move existing compat syscalls for linux under compat folder
Add more compat syscalls for linux
Fix crash on linux when running command that was not found or denied

### CODE REVIEW

**Comment by slicer69** [comment]
I think the conflict with this merge came about because we both fixed the crash on Linux with errc(), but in different ways. I'm going to look at setting up your changes in a branch and maybe using it to replace my solution. My way worked, but I think yours might be cleaner.

**Comment by amalleo25** [comment]
Ah, okay. Somehow I missed your last commit that fixed errc(). I just figured I would reuse what I had already set up for illumos since that seemed to be working well.

**Comment by slicer69** [comment]
I think we were probably working on the fix at the same time. I think yours is better organized so I'm reverting my fix for errc() and applying yours. Since there are a number of files moving or being removed I'm going to test this in a branch and merge it into master later, assuming it works on my test machines. Thanks for sending in the patch.

I'm going to close this pull without an automatic merge, but will merge your patch later manually, once i have a chance to test it.

**Comment by amalleo25** [comment]
Sure, not a problem. Thanks!

**Pull request closed without merging**
