### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by scrouthtv**
Hello,
I am the new maintainer of the Arch Linux User Repositories' doas package.
All the steps (including dependency management) can be simplified for Arch Linux users by simply installing the AUR package.
I added a note to the README for anyone interested.
Greetings

### CODE REVIEW

**Comment by slicer69** [comment]
Thanks for the new information. I have two problems with this change. The first is there is a typo in the link. The second is the new change doesn't provide any information on how to install doas from AUR. I think an example of how to install doas from that repository would be helpful.

**Comment by scrouthtv** [comment]
There aren't really universal instructions for the installation via AUR. Users need an AUR helper which they likely already have installed but there are thirty different.

**Comment by slicer69** [comment]
I realize there are a lot of tools for managing AUR packages. However, I feel we should have at least one example that, when typed into the terminal, is reasonably expected to work. Whether it's makepkg or yay or whatever. Otherwise we are just providing hints without practical instructions.

**Comment by scrouthtv** [comment]
Done

**Comment by slicer69** [comment]
Great, thank you. This looks good. I'll move things around a little to put all the install-from-packages pieces in the same section.

**Pull request merged**
